animal = input("give an animal")
food = input("give a food")
nounOne = input("give a noun")
verbOne = input("give a verb")

print ("if you give a")
print(animal)
print ("a")
print (food)
print ("they are going to ask for a ")
print (nounOne)
print ("when you give them the")
print (nounOne)
print ("they will want to")
print (verbOne)